Synchronized with latest Ash3d.F90

diff --git a/examples/Testcases/TC1/TC1_xy_run b/examples/Testcases/TC1/TC1_xy_run
--- a/examples/Testcases/TC1/TC1_xy_run
+++ b/examples/Testcases/TC1/TC1_xy_run
@@ -6,6 +6,8 @@ ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
 #ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
 TESTCASE=1
 export TESTCASE
+ASH3DCFL=0.99
+export ASH3DCFL
 sub=(0 1 2 3 4 5 6 7 8)
 # Horizontal advection:
 #  subcase 1 : x+y0
@@ -18,18 +20,27 @@ sub=(0 1 2 3 4 5 6 7 8)
 #  subcase 8 : x+y-
 
 # Current limiter options
-#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC
-nlim=(LIM_NONE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_SUPERBEE LIM_MC)
-nlim_label=(LIM_NO LIM_LW LIM_BW LIM_FM LIM_MM LIM_SB LIM_MC)
+#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
+nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
+nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
 #nlim=(LIM_SUPERBEE)
 #nlim_label=(LIM_SB)
 dx=(50000 25000 12500 06250 03125)
-idx=3    # 4
+idx=3    # Approximate duration (minutes) for 7 and 2 limiters, respectively
+         #  1 :     :  
+         #  2 :     ; 
+         #  3 :  16 ; 
+         #  4 :     ; 
+         #  5 : 
 
 limmin=0 # index of above list starting with 0
-limmax=7
+limmax=1
 submin=1 # note the that index 0 is a dummy slot
 submax=8
+
+echo "$idx" > TC1_XY_idx.dat
+echo "$limmin $limmax" > TC1_XY_lim.dat
+echo "$submin $submax" > TC1_XY_sub.dat
 
 echo "*********************************************************"
 echo "Running finite-volume cases (DCU)"
@@ -54,12 +65,18 @@ do
    echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    echo $k ' of ' ${idx}
    echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-   ${ASH3D} TC${TESTCASE}_xy_${dx[k]}.inp
-   mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St1_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_sol.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St2_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_sol.dat
-   rm 3d_tephra_fall*dat
+   ${ASH3D} TC${TESTCASE}_XY_${dx[k]}.inp
+   status=$?
+   if [ $status -ne 0 ]; then
+      echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
+      exit
+    else
+      mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St1_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_sol.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St2_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_sol.dat
+      rm 3d_tephra_fall*dat
+   fi
    echo "-------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------"
diff --git a/examples/Testcases/TC2/TC2_xy_run b/examples/Testcases/TC2/TC2_xy_run
--- a/examples/Testcases/TC2/TC2_xy_run
+++ b/examples/Testcases/TC2/TC2_xy_run
@@ -3,6 +3,7 @@
 ASH3DROOT="../../.."
 WRKDIR="${ASH3DROOT}/src"
 ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
+#ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
 TESTCASE=2
 export TESTCASE
 sub=(0 1 2 3 4)
@@ -13,15 +14,15 @@ sub=(0 1 2 3 4)
 #  subcase 4 : No z wind (fall velocity -)
 
 # Current limiter options
-#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC
-nlim=(LIM_NONE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_SUPERBEE LIM_MC)
-nlim_label=(LIM_NO LIM_LW LIM_BW LIM_FM LIM_MM LIM_SB LIM_MC)
+#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
+nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
+nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
 #nlim_label=(LIM_SB)
 dx=(25000 12500 06250 03125)
-idx=4    # 4
+idx=3    # 4 (should take 20 minutes for 4)
 
 limmin=0 # index of above list starting with 0
-limmax=6
+limmax=2
 submin=1
 submax=4
 
@@ -41,7 +42,7 @@ do
   export LIMITER
   echo $SUBCASE $LIMITER
   make -f makefile_optmod clean
-  make -f makefile_optmod 
+  make -f makefile_optmod
   popd
   for (( k=0;k<idx;k++))
   do
@@ -49,9 +50,15 @@ do
    echo $k ' of ' ${idx}
    echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
-   mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
-   rm 3d_tephra_fall*dat
+   status=$?
+   if [ $status -ne 0 ]; then
+      echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
+      exit
+    else
+      mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
+      rm 3d_tephra_fall*dat
+   fi
    echo "-------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------"
diff --git a/examples/Testcases/TC3/TC3_LL_run b/examples/Testcases/TC3/TC3_LL_run
--- a/examples/Testcases/TC3/TC3_LL_run
+++ b/examples/Testcases/TC3/TC3_LL_run
@@ -3,20 +3,21 @@
 ASH3DROOT="../../.."
 WRKDIR="${ASH3DROOT}/src"
 ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
+#ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
 TESTCASE=3
 export TESTCASE
 
 # Current limiter options
-#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC
-nlim=(LIM_NONE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_SUPERBEE LIM_MC)
-nlim_label=(LIM_NO LIM_LW LIM_BW LIM_FM LIM_MM LIM_SB LIM_MC)
+#      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
+nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
+nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
 #nlim=(LIM_SUPERBEE)
 #nlim_label=(LIM_SB)
 dx=(2000 1000 0500 0250 0125)
-idx=5    # 5
+idx=4    # 5 (should take about 98 minutes for 4)
 
 limmin=0 # index of above list starting with 0
-limmax=6
+limmax=2
 
 echo "*********************************************************"
 echo "Running finite-volume cases (DCU)"
@@ -38,9 +39,15 @@ do
   echo $il ' of ' ${limmas} ' , ' $k ' of ' ${idx}
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   ${ASH3D} TC${TESTCASE}_LL_${dx[k]}.inp
-  mv TC${TESTCASE}_LL_err.dat DATA_LL/TC${TESTCASE}_LL_${nmeth_label[i]}_${nlim_label[il]}_${dx[k]}_err.dat
-  mv TC${TESTCASE}_LL_sol.dat DATA_LL/TC${TESTCASE}_LL_${nmeth_label[i]}_${nlim_label[il]}_${dx[k]}_sol.dat
-  grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA_LL/TC${TESTCASE}_LL_${nlim_label[il]}_etime.dat
+   status=$?
+   if [ $status -ne 0 ]; then
+      echo "ERROR with job ${il}/${k} : ${LIMITER} ${dx[k]} with code=$status"
+      exit
+    else
+      mv TC${TESTCASE}_LL_err.dat DATA_LL/TC${TESTCASE}_LL_${nmeth_label[i]}_${nlim_label[il]}_${dx[k]}_err.dat
+      mv TC${TESTCASE}_LL_sol.dat DATA_LL/TC${TESTCASE}_LL_${nmeth_label[i]}_${nlim_label[il]}_${dx[k]}_sol.dat
+      grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA_LL/TC${TESTCASE}_LL_${nlim_label[il]}_etime.dat
+  fi
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
