Cleaned up and harmonized test cases 1-4.

diff --git a/examples/Testcases/TC3/TC3_LL_run b/examples/Testcases/TC3/TC3_LL_run
--- a/examples/Testcases/TC3/TC3_LL_run
+++ b/examples/Testcases/TC3/TC3_LL_run
@@ -6,30 +6,41 @@ ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
 #ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
 TESTCASE=3
 export TESTCASE
+ASH3DCFL=0.99
+export ASH3DCFL
+
+# Subcases
+#  Only one case: Rigid rotation of block and cone concentration
 
 # Current limiter options
 #      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
 nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
 nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
-#nlim=(LIM_SUPERBEE)
-#nlim_label=(LIM_SB)
 dx=(2000 1000 0500 0250 0125)
-idx=3    # 5 (should take about 98 minutes for 4)
+idx=3    # Approximate duration (minutes) for 7 and 2 limiters, respectively
+         #  1 :     :  
+         #  2 :     : 
+         #  3 :     : 
+         #  4 :     : 
+         #  5 : 
 
 limmin=0 # index of above list starting with 0
-limmax=2
+limmax=6
+
+echo "$idx" > TC3_LL_idx.dat
+echo "$limmin $limmax" > TC3_LL_lim.dat
 
 echo "*********************************************************"
 echo "Running finite-volume cases (DCU)"
 echo "*********************************************************"
 
-mkdir -p DATA_LL
-
+mkdir -p DATA
 for (( il=$limmin;il<=$limmax;il++))
 do
  pushd ${WRKDIR}
  LIMITER=${nlim[il]}
  export LIMITER
+ echo $LIMITER
  make -f makefile_optmod clean
  make -f makefile_optmod
  popd
@@ -39,14 +50,14 @@ do
   echo $il ' of ' ${limmas} ' , ' $k ' of ' ${idx}
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   ${ASH3D} TC${TESTCASE}_LL_${dx[k]}.inp
-   status=$?
-   if [ $status -ne 0 ]; then
-      echo "ERROR with job ${il}/${k} : ${LIMITER} ${dx[k]} with code=$status"
-      exit
-    else
-      mv TC${TESTCASE}_LL_err.dat DATA_LL/TC${TESTCASE}_LL_${nmeth_label[i]}_${nlim_label[il]}_${dx[k]}_err.dat
-      mv TC${TESTCASE}_LL_sol.dat DATA_LL/TC${TESTCASE}_LL_${nmeth_label[i]}_${nlim_label[il]}_${dx[k]}_sol.dat
-      grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA/TC${TESTCASE}_LL_${nlim_label[il]}_etime.dat
+  status=$?
+  if [ $status -ne 0 ]; then
+     echo "ERROR with job ${il}/${k} : ${LIMITER} ${dx[k]} with code=$status"
+     exit
+   else
+     mv TC${TESTCASE}_LL_err.dat DATA/TC${TESTCASE}_LL_${nlim_label[il]}_${dx[k]}_err.dat
+     mv TC${TESTCASE}_LL_sol.dat DATA/TC${TESTCASE}_LL_${nlim_label[il]}_${dx[k]}_sol.dat
+     grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA/TC${TESTCASE}_LL_${nlim_label[il]}_etime.dat
   fi
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
