Brought TC 1-3 up-to-date with latest version of Ash3d. Added error-checking to run scripts.

diff --git a/examples/Testcases/TC2/TC2_xy_run b/examples/Testcases/TC2/TC2_xy_run
--- a/examples/Testcases/TC2/TC2_xy_run
+++ b/examples/Testcases/TC2/TC2_xy_run
@@ -6,6 +6,10 @@ ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
 #ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
 TESTCASE=2
 export TESTCASE
+ASH3DCFL=0.99
+export ASH3DCFL
+
+# Subcases
 sub=(0 1 2 3 4)
 # Vertical advection:
 #  subcase 1 : Wind blows up (no fall velocity)
@@ -14,29 +18,25 @@ sub=(0 1 2 3 4)
 #  subcase 4 : No z wind (fall velocity -)
 
 # Current limiter options
-<<<<<<< HEAD
 #      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
 nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
 nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
-#nlim_label=(LIM_SB)
-dx=(25000 12500 06250 03125)
-idx=3    # 4 (should take 20 minutes for 4)
-
-limmin=0 # index of above list starting with 0
-limmax=2
-=======
-#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC
-nlim=(LIM_NONE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_SUPERBEE LIM_MC)
-nlim_label=(LIM_NO LIM_LW LIM_BW LIM_FM LIM_MM LIM_SB LIM_MC)
-
 dx=(50000 25000 12500 06250 03125)
-idx=5    # 5
+idx=3    # Approximate duration (minutes) for 7 and 2 limiters, respectively
+         #  1 :     :  
+         #  2 :     ; 
+         #  3 :     ; 
+         #  4 :     ; 
+         #  5 : 
 
 limmin=0 # index of above list starting with 0
 limmax=7
->>>>>>> f628dc1caa97b0b7f2f4f7e9241a5b90f92a6629
 submin=1
 submax=4
+
+echo "$idx" > TC2_XY_idx.dat
+echo "$limmin $limmax" > TC2_XY_lim.dat
+echo "$submin $submax" > TC2_XY_sub.dat
 
 echo "*********************************************************"
 echo "Running finite-volume cases (DCU)"
@@ -61,18 +61,6 @@ do
    echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
    echo $k ' of ' ${idx}
    echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-<<<<<<< HEAD
-   ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
-   status=$?
-   if [ $status -ne 0 ]; then
-      echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
-      exit
-    else
-      mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
-      mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
-      rm 3d_tephra_fall*dat
-   fi
-=======
    if [ "${is}" -eq "1" ] ; then
      ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
    elif [ "${is}" -eq "2" ] ; then
@@ -82,13 +70,17 @@ do
    elif [ "${is}" -eq "4" ] ; then
      ${ASH3D} TC${TESTCASE}_S4_${dx[k]}.inp
    fi
-   #${ASH3D} TC${TESTCASE}_${dx[k]}.inp
-   mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St1_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_sol.dat
-   mv TC${TESTCASE}_Sub${SUBCASE}_St2_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_sol.dat
-   rm 3d_tephra_fall*dat
->>>>>>> f628dc1caa97b0b7f2f4f7e9241a5b90f92a6629
+   status=$?
+   if [ $status -ne 0 ]; then
+      echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
+      exit
+    else
+      mv TC${TESTCASE}_Sub${SUBCASE}_St1_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_err.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St2_err.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_err.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St1_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St1_sol.dat
+      mv TC${TESTCASE}_Sub${SUBCASE}_St2_sol.dat DATA/TC${TESTCASE}_XY_Sub${SUBCASE}_${nlim_label[il]}_${dx[k]}_St2_sol.dat
+      rm 3d_tephra_fall*dat
+   fi
    echo "-------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------"
diff --git a/examples/Testcases/TC3/TC3_xyz_run b/examples/Testcases/TC3/TC3_xyz_run
--- a/examples/Testcases/TC3/TC3_xyz_run
+++ b/examples/Testcases/TC3/TC3_xyz_run
@@ -4,43 +4,43 @@ ASH3DROOT="../../.."
 WRKDIR="${ASH3DROOT}/src"
 ASH3D="${ASH3DROOT}/bin/Ash3d_TC"
 #ASH3D="${ASH3DROOT}/bin/Ash3d_TC_debug"
-TESTCASE=1
+TESTCASE=3
 export TESTCASE
+ASH3DCFL=0.99
+export ASH3DCFL
+
+# Subcases
+#  Only one case: Rigid rotation of block and cone concentration
 
 # Current limiter options
-<<<<<<< HEAD
 #      LIM_NONE,LIM_SUPERBEE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_MC
 nlim=(LIM_NONE LIM_SUPERBEE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_MC)
 nlim_label=(LIM_NO LIM_SB LIM_LW LIM_BW LIM_FM LIM_MM LIM_MC)
-#nlim=(LIM_SUPERBEE)
-#nlim_label=(LIM_SB)
-=======
-#      LIM_NONE,LIM_LAXWEN,LIM_BW,LIN_FROMM,LIM_MINMOD,LIM_SUPERBEE,LIM_MC
-nlim=(LIM_NONE LIM_LAXWEN LIM_BW LIM_FROMM LIM_MINMOD LIM_SUPERBEE LIM_MC)
-nlim_label=(LIM_NO LIM_LW LIM_BW LIM_FM LIM_MM LIM_SB LIM_MC)
-
->>>>>>> f628dc1caa97b0b7f2f4f7e9241a5b90f92a6629
 dx=(50000 25000 12500 06250 03125)
-idx=3    # 5
+idx=1    # Approximate duration (minutes) for 7 and 2 limiters, respectively
+         #  1 :     :  
+         #  2 :     ; 
+         #  3 :  16 ; 
+         #  4 :     ; 
+         #  5 : 
 
 limmin=0 # index of above list starting with 0
-<<<<<<< HEAD
 limmax=0
-=======
-limmax=7
->>>>>>> f628dc1caa97b0b7f2f4f7e9241a5b90f92a6629
+
+echo "$idx" > TC3_XY_idx.dat
+echo "$limmin $limmax" > TC3_XY_lim.dat
 
 echo "*********************************************************"
 echo "Running finite-volume cases (DCU)"
 echo "*********************************************************"
 
 mkdir -p DATA_xy
-
 for (( il=$limmin;il<=$limmax;il++))
 do
  pushd ${WRKDIR}
  LIMITER=${nlim[il]}
  export LIMITER
+ echo $LIMITER
  make -f makefile_optmod clean
  make -f makefile_optmod
  popd
@@ -50,9 +50,15 @@ do
   echo $il ' of ' ${limmas} ' , ' $k ' of ' ${idx}
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   ${ASH3D} TC${TESTCASE}_${dx[k]}.inp
-  mv TC${TESTCASE}_err.dat DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_err.dat
-  mv TC${TESTCASE}_sol.dat DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_sol.dat
-  grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_etime.dat
+  status=$?
+  if [ $status -ne 0 ]; then
+     echo "ERROR with job ${is}/${il}/${k} : ${SUBCASE} ${LIMITER} ${dx[k]} with code=$status"
+     exit
+   else
+     mv TC${TESTCASE}_err.dat DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_err.dat
+     mv TC${TESTCASE}_sol.dat DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_${dx[k]}_sol.dat
+     grep Execution Ash3d.lst | grep -v CPU | cut -c 35-48 >> DATA_xy/TC${TESTCASE}_XY_${nlim_label[il]}_etime.dat
+  fi
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
   echo "-------------------------------------------------------------------------"
